# Google App Engine - Standard Environment
# Copy to your project root and customize

runtime: python312
instance_class: F2

# Application entrypoint
entrypoint: gunicorn -b :$PORT myproject.wsgi:application

# Environment variables (NOT for secrets - use Secret Manager)
env_variables:
  DJANGO_SETTINGS_MODULE: "myproject.settings.production"
  GOOGLE_CLOUD_PROJECT: "your-project-id"

# Cloud SQL connection (REQUIRED for database)
beta_settings:
  cloud_sql_instances: "your-project:your-region:your-instance"

# Request handlers
handlers:
  # Static files - served directly by App Engine
  - url: /static
    static_dir: staticfiles/
    secure: always
    expiration: "1d"

  # All other requests go to the application
  - url: /.*
    script: auto
    secure: always

# Scaling configuration
automatic_scaling:
  min_instances: 0          # Scale to zero when idle (cost savings)
  max_instances: 10         # Cap maximum instances
  target_cpu_utilization: 0.65
  max_concurrent_requests: 80

# Health checks
liveness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Enable warmup requests to reduce cold starts
inbound_services:
  - warmup
