# =============================================================================
# App Engine Configuration for Django with Cloud SQL PostgreSQL
# =============================================================================
#
# Usage:
#   1. Replace 'myproject' with your Django project name
#   2. Replace 'project-id:us-central1:instance-name' with your Cloud SQL connection
#   3. Set DB_PASSWORD via: gcloud app deploy --set-env-vars="DB_PASSWORD=xxx"
#   4. Deploy: gcloud app deploy app.yaml
#
# =============================================================================

runtime: python310

# Gunicorn entrypoint
# -b :$PORT  = Bind to App Engine's PORT
# -w 2       = 2 workers (F2 instance max)
# -t 55      = 55 second timeout (under App Engine's 60s limit)
# --threads 4 = 4 threads per worker for I/O-bound requests
entrypoint: gunicorn -b :$PORT -w 2 -t 55 --threads 4 myproject.wsgi:application

# Instance class (F2 allows 2 workers, F1 only allows 1)
instance_class: F2

# Environment variables
# IMPORTANT: Do NOT put DB_PASSWORD here - set via gcloud deploy command
env_variables:
  DB_NAME: "mydb"
  DB_USER: "postgres"
  CLOUD_SQL_CONNECTION_NAME: "project-id:us-central1:instance-name"
  DEBUG: "False"
  # Set at deploy time:
  # gcloud app deploy --set-env-vars="DB_PASSWORD=xxx,SECRET_KEY=xxx"

# Cloud SQL connection - creates Unix socket at /cloudsql/CONNECTION_NAME
beta_settings:
  cloud_sql_instances: "project-id:us-central1:instance-name"

# Request handlers
handlers:
  # Static files (served directly, not through Django)
  - url: /static
    static_dir: static/
    secure: always
    http_headers:
      Cache-Control: "public, max-age=3600"

  # Favicon
  - url: /favicon\.ico
    static_files: static/favicon.ico
    upload: static/favicon\.ico
    secure: always

  # All other requests go to Django
  - url: /.*
    script: auto
    secure: always

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0        # Scale to zero when idle (saves costs)
  max_instances: 2        # Limit max instances
  target_cpu_utilization: 0.65

  # Request handling
  max_concurrent_requests: 80
  target_throughput_utilization: 0.6

# Optional: Warmup requests (reduces cold start impact)
# inbound_services:
#   - warmup

# =============================================================================
# Deployment Commands Reference
# =============================================================================
#
# First deployment:
#   gcloud app create --region=us-central1
#   python manage.py collectstatic --noinput
#   gcloud app deploy app.yaml --set-env-vars="DB_PASSWORD=xxx,SECRET_KEY=xxx"
#
# Update deployment:
#   python manage.py collectstatic --noinput
#   gcloud app deploy app.yaml
#
# View logs:
#   gcloud app logs tail -s default
#
# Open in browser:
#   gcloud app browse
#
# =============================================================================
